### ISSUE TITLE
Loading playlists - incomplete?

### ISSUE THREAD

**Issue by txnico** [eightants/whisperify#48]
Nice work with the project! 

When loading playlists for a user, it does not seem to be returning all user playlists. Is there a delay or some other limitation for getting a users' playlists?

Thanks!

**Comment by eightants** [comment]
Hi, thanks for opening the issue! 

Playlists with less than 30 songs are not shown in the list, since the quizzes generated using them will usually contain the same songs. Other than that, all playlists followed or created by the user should be showing. 

If the 30 song minimum for playlists is an issue, I can look into reducing it down to a lower limit.

**Comment by txnico** [comment]
Ah, yes. I can see that now. 

My use case today is a trivia game for remote teams. I was hoping to create a handful of playlists with 5-7 songs each and go through each playlist 'quiz' in Whisperfy. 

Thanks for the response!

**Comment by eightants** [comment]
I see, I think that's a valid use case. Currently Whisperify does not support quizzes with less than 10 questions, but I can lower the limit for playlists to 15 songs and that might be good!

**Comment by eightants** [comment]
Updated with #50
